services:

  db:
    container_name: db
    build:
      context: ./postgres

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  app:
    container_name: app
    build:
      context: ./app
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
