services:

  db:
    container_name: db
    build:
      context: ./postgres

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./app
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume:
